This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./Bachelorarbeit.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Bachelorarbeit.acn....done (96 entries accepted, 0 rejected).
Sorting entries....done (658 comparisons).
Generating output file Bachelorarbeit.acr....done (77 lines written, 0 warnings).
Output written in Bachelorarbeit.acr.
Transcript written in Bachelorarbeit.alg.
